# Generated by Django 4.0.4 on 2022-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_descripcion_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='descripciones'),
        ),
    ]
